#define RAYGUI_IMPLEMENTATION
#include "raylib.h"
#include "raygui.h" 
#include "game_types.h"
#include <stdio.h>

// We need a list of entities for the editor, separate from the game simulation
Entity editorEntities[MAX_ENTITIES];
int editorCount = 0;

// Current selection settings
int selectedType = ENTITY_WALL; 
float selectedWidth = 100.0f;
float selectedHeight = 100.0f;

// --- FILE I/O (WRITER) ---
void SaveLevel(const char* filename) {
    FILE* file = fopen(filename, "w");
    if (!file) {
        printf("Could not save file to: %s\n", filename);
        return;
    }

    fprintf(file, "# Generated by C-Engine Editor\n");
    
    for (int i = 0; i < editorCount; i++) {
        Entity* e = &editorEntities[i];
        if (!e->active) continue;

        // FORMAT: TYPE X Y [W H]
        if (e->type == ENTITY_SNAKE) {
            fprintf(file, "P %d %d\n", (int)e->position.x, (int)e->position.y);
        }
        else if (e->type == ENTITY_APPLE) {
            fprintf(file, "A %d %d\n", (int)e->position.x, (int)e->position.y);
        }
        else if (e->type == ENTITY_WALL) {
            fprintf(file, "W %d %d %d %d\n", 
                (int)e->position.x, (int)e->position.y, 
                (int)e->size.x, (int)e->size.y);
        }
    }

    fclose(file);
    printf("Level Saved to %s\n", filename);
}

void LoadLevelForEditor(const char* filename) {
    // Logic to load existing levels into editor would go here
    editorCount = 0;
}

// --- MAIN EDITOR LOOP ---
int main() {
    InitWindow(1000, 600, "Level Editor - Unity Style"); 
    SetTargetFPS(60);

    bool showGrid = true;
    int activeTool = 0; // 0 = Paint, 1 = Erase

    while (!WindowShouldClose()) {
        Vector2 mousePos = GetMousePosition();
        
        // Snap to Grid (50px)
        int gridX = (int)(mousePos.x / 50) * 50;
        int gridY = (int)(mousePos.y / 50) * 50;

        // Input Handling (Only inside Game Area)
        if (mousePos.x < 800) { 
            if (IsMouseButtonDown(MOUSE_LEFT_BUTTON)) {
                if (activeTool == 0) {
                    // Prevent stacking duplicates
                    bool exists = false;
                    for(int i=0; i<editorCount; i++) {
                         if(editorEntities[i].active && 
                            editorEntities[i].position.x == gridX && 
                            editorEntities[i].position.y == gridY) {
                             exists = true; 
                             break;
                         }
                    }

                    if (!exists && editorCount < MAX_ENTITIES) {
                        Entity* e = &editorEntities[editorCount++];
                        e->active = true;
                        e->type = selectedType;
                        e->position = (Vector2){(float)gridX, (float)gridY};
                        e->size = (Vector2){selectedWidth, selectedHeight};
                    }
                }
                else if (activeTool == 1) {
                    // Erase Tool
                    for(int i=0; i<editorCount; i++) {
                        Entity* e = &editorEntities[i];
                        if (e->active && 
                            mousePos.x >= e->position.x && mousePos.x < e->position.x + e->size.x &&
                            mousePos.y >= e->position.y && mousePos.y < e->position.y + e->size.y) {
                            e->active = false; 
                        }
                    }
                }
            }
        }

        BeginDrawing();
        ClearBackground(DARKGRAY);

        // Draw Game Area Background
        DrawRectangle(0, 0, 800, 600, BLACK);
        
        // Draw Grid Lines
        if (showGrid) {
            for(int i=0; i<800; i+=50) DrawLine(i, 0, i, 600, Fade(WHITE, 0.1f));
            for(int i=0; i<600; i+=50) DrawLine(0, i, 800, i, Fade(WHITE, 0.1f));
        }

        // Draw Placed Entities
        for (int i = 0; i < editorCount; i++) {
            Entity* e = &editorEntities[i];
            if (!e->active) continue;

            Color c = WHITE;
            if (e->type == ENTITY_WALL) c = BLUE;
            if (e->type == ENTITY_SNAKE) c = GREEN;
            if (e->type == ENTITY_APPLE) c = RED;

            DrawRectangleV(e->position, e->size, c);
            DrawRectangleLines(e->position.x, e->position.y, e->size.x, e->size.y, WHITE);
        }

        // Draw "Ghost" Preview
        if (mousePos.x < 800 && activeTool == 0) {
            Color ghostColor = WHITE;
            if (selectedType == ENTITY_WALL) ghostColor = Fade(BLUE, 0.5f);
            if (selectedType == ENTITY_SNAKE) ghostColor = Fade(GREEN, 0.5f);
            if (selectedType == ENTITY_APPLE) ghostColor = Fade(RED, 0.5f);
            
            DrawRectangle(gridX, gridY, (int)selectedWidth, (int)selectedHeight, ghostColor);
        }

        // --- SIDEBAR GUI ---
        DrawRectangle(800, 0, 200, 600, LIGHTGRAY); 
        
        GuiLabel((Rectangle){810, 10, 180, 20}, "ASSET PALETTE");

        // Tools
        if (GuiButton((Rectangle){810, 40, 80, 30}, "PAINT")) activeTool = 0;
        if (GuiButton((Rectangle){900, 40, 80, 30}, "ERASE")) activeTool = 1;
        GuiLabel((Rectangle){810, 75, 180, 20}, (activeTool == 0) ? "Mode: PAINT" : "Mode: ERASE");

        // Entity Types
        GuiLabel((Rectangle){810, 110, 180, 20}, "Select Type:");
        if (GuiButton((Rectangle){810, 130, 180, 30}, "WALL")) {
            selectedType = ENTITY_WALL;
            selectedWidth = 50; selectedHeight = 200; 
        }
        if (GuiButton((Rectangle){810, 170, 180, 30}, "SNAKE SPAWN")) {
            selectedType = ENTITY_SNAKE;
            selectedWidth = 20; selectedHeight = 20;
        }
        if (GuiButton((Rectangle){810, 210, 180, 30}, "APPLE")) {
            selectedType = ENTITY_APPLE;
            selectedWidth = 20; selectedHeight = 20;
        }

        // Size Sliders
        GuiLabel((Rectangle){810, 260, 180, 20}, "Custom Size:");
        GuiSlider((Rectangle){850, 290, 130, 20}, "W", NULL, &selectedWidth, 20, 500);
        GuiSlider((Rectangle){850, 320, 130, 20}, "H", NULL, &selectedHeight, 20, 500);

        // SAVE BUTTON (Fixed Path)
        if (GuiButton((Rectangle){810, 550, 180, 40}, "SAVE LEVEL")) {
            // "assets/" means: Look in the current folder for a folder named assets
            SaveLevel("assets/level1.eng");
        }

        EndDrawing();
    }

    CloseWindow();
    return 0;
}